sudo: required
dist: trusty

language: python

python:
  - "2.7_with_system_site_packages"

env:
  - TOX_ENV=py27
  - TOX_ENV=py35
  - TOX_ENV=docs
  - TOX_ENV=flake8

before_install:
  - "sudo apt-get update -qq"
  - "sudo apt-get install -y graphviz-dev gstreamer0.10-plugins-good python-gst0.10"

install:
  - "pip install tox"

script:
  - "tox -e $TOX_ENV"

after_success:
  - "if [ $TOX_ENV == 'py27' ]; then pip install coveralls; coveralls; fi"

branches:
  except:
    - debian
