version: '2'
services:
  web:
    build: .
    ports:
      - "8080:8080"
    links:
      - redis
      - rabbitmq
    entrypoint: frontend

  worker:
    build: .
    links:
      - rabbitmq
      - redis
    entrypoint: backend

  redis:
    image: redis:alpine
    expose:
      - "6379"

  rabbitmq:
    image: rabbitmq:management
    ports:
      - "15672:15672"
    expose:
      - "5672"


