web:
  build: .
  ports:
    - "8080:8080"
  links:
    - redis
    - rabbitmq
worker:
  build: .
  links:
    - redis
    - rabbitmq
redis:
  image: redis

rabbitmq:
  image: management
  ports:
    - "15672:15672"
 

